### ISSUE TITLE
Consistency between error logging and logging guidelines

### ISSUE THREAD

**Issue by peppemanzi** [mia-platform/lc39#217]
## Description of the issue
[Logging guidelines](https://docs.mia-platform.eu/docs/getting_started/monitoring-dashboard/dev_ops_guide/log#errors) for Mia-Platform PaaS environment requires errors to be logged using `error` key. Since the default configuration for error serialization is used for _pino.js_, errors logged using `error` key are stringified by _lc39_'s logger as an empty object (`{}`). Currently, in order to have a correctly logged error, `err` key must be used, as described in [pino.js docs](https://github.com/pinojs/pino/blob/master/docs/api.md#errors), however this implies that errors are not indexed by the logging system. 

## A snippet of code for replicating the issue or showing the proposal usage if applicable
main.js:
```'use strict'

const launch = require('lc39')

launch('./example.js', {logLevel: 'debug'})
```
example.js:
```'use strict'

module.exports = async function plugin(fastify) {
  fastify.log.error({
    err: new Error('correctly serialized'),
    error: new Error('wrongly serialized')
  })
}
```

## The expected result
Guidelines and logs indexing must be adapted to handle `err` key and/or values having `error` key should be serialized if they are instances of JavaScript `Error` class

**Comment by davidebianchi** [comment]
So, we add the serializer for the error field in addition to the already existend serialization of error. 
Correct?

**Comment by peppemanzi** [comment]
> So, we add the serializer for the error field in addition to the already existend serialization of error.
> Correct?
Yes, I think it could be a good solution
