### ISSUE TITLE
Schema validation: `anyOf` and `oneOf` are broken

### ISSUE THREAD

**Issue by mattia-fumo** [mia-platform/lc39#222]
## The feature or bug you are proposing
Using a schema with `anyOf` or `oneOf` doesn't behave as expected.

## The description of the bug or the rationale of your proposal
Composed schemas, with `anyOf` or `oneOf`, are wrongly validated. In particular, only the first element of the schemas array gets properly validated, other elements never get validated and are reported as an error even if they match the provided schema.

## A snippet of code for replicating the issue or showing the proposal usage if applicable
Given the following schema associated with an arbitrary `POST` endpoint:
```json
{
   "type":"object",
   "anyOf":[
      {
         "type": "object",
         "required": [ "a" ],
         "properties": {
            "a": { "type": "string" }
         }
      },
      {
         "type": "object",
         "required": [ "b" ],
         "properties": {
            "b": { "type": "string" }
         }
      }
   ]
}
```

Submitting a request with the following body gets successfully validated:

```json
{ "a": "value" }
```

While a request with this other body returns an error:

```json
{ "b": "value" }
```

## The expected result for your bug

Both requests' bodies are successfully validated.

**Comment by davidebianchi** [comment]
Hi @mattia-fumo! The schema validation is the validation done by fastify when a request incoming? In this case, it is an issue of fastify I suppose.
