### ISSUE TITLE
Update to fastify 4

### ISSUE THREAD

**Issue by theliuk** [mia-platform/lc39#248]
When are we going to update fastify to v4?

Thanks,

Luca

**Comment by davidebianchi** [comment]
There is already the prerelease version `v7.0.0-rc.0` with the upgrade to fastify v4 to start with. But it should do some tests

**Comment by theliuk** [comment]
Hi @davidebianchi,
ok, so we have to wait a while before upgrading to v7, am I correct? 

Do you have an estimate release time? 
Will be there any breaking chances to be aware of?

Thanks,

Luca

**Comment by davidebianchi** [comment]
All the breaking changes of fastify v4, but if I remember well in the RC release it should be present a changelog of all the breaking changes discovered at the time of the release
