### ISSUE TITLE
Service prefix validation

### ISSUE THREAD

**Issue by davidebianchi** [mia-platform/lc39#8]
Why we support only service prefix with a trailing slash?

https://github.com/mia-platform/lc39/blob/f7716888c1389c00d9c194d260a4236acd3bcdf5/lib/launch-fastify.js#L49-L59

**Comment by allevo** [comment]
It seems to be handled correctly:

Fastify v2
https://github.com/fastify/fastify/blob/772cf5eb9fb3565f237630fb5a6790808ac07688/test/route-prefix.test.js#L227

fastify v1
https://github.com/fastify/fastify/blob/e716f894725cee99156e68d5932e00c857232b12/test/route-prefix.test.js#L227
