### ISSUE TITLE
Metrics endpoint

### ISSUE THREAD

**Issue by giulioroggero** [mia-platform/lc39#9]
Add /metrics endpoint for prometheus https://prometheus.io/docs/prometheus/latest/getting_started/

TOBE detailed.

**Comment by davidebianchi** [comment]
This is added in v3 of the lib. Documentation could be found here: https://github.com/mia-platform/lc39/blob/master/docs/main-entrypoint.md#prometheus-metrics

Please, reopen if it is not the desired feature.
